### ISSUE TITLE
Each user must have App? 

### ISSUE THREAD

**Issue by Moka51** [Rehan989/reddit-upvote-bot#1]
All users added to the password list must have their own app?

Or can it be only one that has the app and the rest only users and password? Thanks in advanced

**Comment by Rehan989** [comment]
See we need apps because for praw we have to do get the client secret and client key.
And I am currently working on the selenium bot.
Wait for that to be published.

**Comment by Rehan989** [comment]
> All users added to the password list must have their own app?
> 
> Or can it be only one that has the app and the rest only users and password? Thanks in advanced
