### ISSUE TITLE
Upvotes disappear

### ISSUE THREAD

**Issue by AlphaLikesMC** [Rehan989/reddit-upvote-bot#2]
Hey, upvotes do come but after a while they disappear, might you know the reason behind this? Please help me with this as I'd love to get it working.

**Comment by Rehan989** [comment]
See I also have this issue before,
Are you using praw?

**Comment by Rehan989** [comment]
Yes i Know that because i think we have to use the proxy,
many logins from one IP seems like a bot that's why this issue happens.
I am still looking into this issue.
I am working on the selenium reddit bot.
Wait for that to be published

**Comment by AlphaLikesMC** [comment]
Going the selenium route would be slower, no way to add proxies to this? Like it would rotate through a list of proxies and upvote using dif proxy for each account.

**Comment by Rehan989** [comment]
> Going the selenium route would be slower, no way to add proxies to this? Like it would rotate through a list of proxies and upvote using dif proxy for each account.

You can improve the code if you want

**Comment by Rehan989** [comment]
> Going the selenium route would be slower, no way to add proxies to this? Like it would rotate through a list of proxies and upvote using dif proxy for each account.

You can run multiple instances of selenium code.
However selenuim votes are not working

**Comment by AlphaLikesMC** [comment]
> > Going the selenium route would be slower, no way to add proxies to this? Like it would rotate through a list of proxies and upvote using dif proxy for each account.
> 
> You can improve the code if you want

Yup I've tried. I tried doing selenium but it doesn't work like you said. I also tried adding proxies to your same code and each account uses a different proxy to upvote but the same happened like before, upvotes came but then disappeared...

So I assume it doesn't have to do with proxies or anything and the trick is something else entirely.

**Comment by Rehan989** [comment]
> > > Going the selenium route would be slower, no way to add proxies to this? Like it would rotate through a list of proxies and upvote using dif proxy for each account.
> > 
> > 
> > You can improve the code if you want
> 
> Yup I've tried. I tried doing selenium but it doesn't work like you said. I also tried adding proxies to your same code and each account uses a different proxy to upvote but the same happened like before, upvotes came but then disappeared...
> 
> So I assume it doesn't have to do with proxies or anything and the trick is something else entirely.

Yes you are absolutely correct!

**Comment by Rehan989** [comment]
Do you know why upvotes are decreasing?

**Comment by AlphaLikesMC** [comment]
No clue man, I think it's just because it's detecting the upvotes are coming from same pc somehow, even though I tried changing everything for each account, no idea, doesn't work...

**Comment by Rehan989** [comment]
yes, have you saw the redditboost.com do you know how it is working?

**Comment by Rehan989** [comment]
And do you know how to use proxies with praw??
